### ISSUE TITLE
iOS 11 - AR.js Doesn't work on Chrome; does work on Safarai

### ISSUE THREAD

**Issue by quistuipater** [jeromeetienne/AR.js#204]
With Safari on iOS 11 AR.js works great but fails on Chrome 61.

**Comment by dubyajaysmith** [comment]
iOS makes other browser use it's webkit and it seems chrome needs to take advantage now that webrtc is available.  This seems to be across the board on webrtc projects.

**Comment by kmcurry** [comment]
![e9df4ab3-e094-40bd-b2ec-9b7c4e631312](https://user-images.githubusercontent.com/69151/32875153-63f13fc6-ca64-11e7-9994-8b69db96f75e.png)
![eb1784fa-6f4c-4cdc-8016-4bbb430ed4af](https://user-images.githubusercontent.com/69151/32875154-63fcf460-ca64-11e7-8616-cdae8235fcb5.png)

**Comment by ZoltanVeres** [comment]
On iOS, Chrome is actually a Safari browser (because Apple is not allowing other browser engines in it's ecosystem) with the UI of Chrome. But Chrome is not automatically getting the latest version of Safari, they have to manually update their Safari engine and deliver the change settings via an app-update. By the time of running this demo, i suspecting that Chrome used an older version of Safari (under the hood), thus the error in the screenshot. In any case if the issue is still persists, send us the link and we'll test it out and point you to a fix, until then this issue remains closed. Thanks!

**Comment by MartinVollenweider** [comment]
Just fyi: On Chrome 63.0 on iOS 11.2.1 it is still not working.

**Comment by Tiberriver256** [comment]
Still an issue

**Comment by navanchauhan** [comment]
Still an issue

**Comment by droid001** [comment]
And probably won't until Apple enables fully WebRTC and in particular `navigator.mediaDevices.getUserMedia`. See [caniuse](https://caniuse.com/#feat=stream) footnote #3:
 

> Does not work in standalone running ("installed") PWAs, getUserMedia returns no video input devices in UIWebView or WKWebView, but only directly in Safari.
This is also a painpoint when creating a PWA for iOS. Had to revert to a VR version of the project I was working on.
