### ISSUE TITLE
Rotation and Stretch problems ( iOs® and Android® )

### ISSUE THREAD

**Issue by AndreaMonzini** [jeromeetienne/AR.js#242]
Hello,
i did some test and i see 3D Rotation and 3D Stretch problems on  iOs® and Android® devices and it seems they  related also to the orientation of the Devices in the space beside the portrait mode:

Tested on  iPad® Air,  iPhone® ( iOs® 11 ) and Android® Phone ( Firefox® 56  , Chrome® 61 ) 

- in portrait mode, if the iPAd®, iPhone® or Android® Phone  are Vertical ( parallel to the wall) and the marker is on the wall: wrong rotation of the 3D content and 3D is also stretched.
- in portrait mode, if the iPAd®, iPhone® or Android® Phone are Horizontal ( Parallel to the table) and the marker is on the table: correct rotation of the 3D content but 3D is stretched.

- In landscape mode if the iPAd®, iPhone® or Android® Phone are Vertical ( parallel to the wall) and the marker is on the table: works well
- In landscape mode if the iPAd®,iPhone® or Android® Phone are Horizontal ( Parallel to the table)  and the marker is on the table: works well

Conclusion: 

- The 3D Rotation and 3D Stretch problems are related to iOs® and Android®
- We can reproduce the 3D Rotation problem with Portrait mode, vertical device (  parallel to the wall) and marker on the wall.
- We can reproduce the 3D Stretch problem with Portrait mode, vertical/horizontal device (  parallel to the wall or parallel to the table ), and markers on the wall or on the table.
Related to:
https://github.com/jeromeetienne/AR.js/issues/128 https://github.com/jeromeetienne/AR.js/issues/229 https://github.com/jeromeetienne/AR.js/issues/228 https://github.com/jeromeetienne/AR.js/issues/275
https://github.com/jeromeetienne/AR.js/issues/289

Solutions:
https://github.com/jeromeetienne/AR.js/pull/212 https://github.com/jeromeetienne/AR.js/issues/246

**Comment by javismiles** [comment]
That's exactly right, I have been testing in both laptop PC and android/iOS and yes the stretching happens on mobile devices

**Comment by Adolar13** [comment]
Hey @javismiles I tried the changes from @pikilipita in #212. Works for me.
I attached the aframe-ar.js with the changes, while it's not merged in the main branch.
[aframe-ar.zip](https://github.com/jeromeetienne/AR.js/files/1461777/aframe-ar.zip)

**Comment by javismiles** [comment]
@Adolar13 thank you very much, really appreciated, i wonder if this will fix all the distorsion issues i had  found on android, thank you again

**Comment by AndreaMonzini** [comment]
Just tested it and the problems seem solved! ( just the overlay buttons position seems shifted )
Thank you  @pikilipita and  @Adolar13 !

**Comment by javismiles** [comment]
thank you again , this fix seems to work well, can you guys help with another issue related to clicks?

my marker when detected activates and shows a video (I use a-frame with ar.js, so aframe-ar), 
I want to detect a click on that video element, not on the whole screen, for some reason yes I can detect a click but its detected in the entire whole screen, instead of just
in the video element itself, how can I make sure that it happens on the video element itself?

Also I am using onclick events now because this used to work:

AFRAME.registerComponent('javi1', {
    init: function () {
      var el = this.el; 
	  el.addEventListener('click', function (evt) {... etc

but now its not working anymore  for some reason,

what's your recommended way to detect a click on the specific video element?

btw, in console Im receiving these 2 warnings, do they have any relation to the issues with clicks?
"THREE.WebGLRenderer 87
pictoar1js.min.js:3 extras:primitives:warn Mapping keys should be specified in lower case. The mapping key minConfidence may not be recognized 
pictoar1js.min.js:3 extras:primitives:warn Mapping keys should be specified in lower case. The mapping key hit-testing-renderDebug may not be recognized "

thanks a lot

**Comment by AndreaMonzini** [comment]
hello @javismiles I'm trying to test video  with ios® using `webkit-playsinline` and `playsinline` but the video does not start, do you have a working project example  ?
Thank you.

**Comment by AndreaMonzini** [comment]
@javismiles thank you ! tomorrow i will try video in AR.js again ;)

**Comment by lslzl3000** [comment]
Also working on the roataion and strech problem~
Is there a plan to fix this issue or merge into main branch?

**Comment by AndreaMonzini** [comment]
Waiting for main branch, we have these solutions:

Solutions:
https://github.com/jeromeetienne/AR.js/pull/212 https://github.com/jeromeetienne/AR.js/issues/246

**Comment by nicolocarpignoli** [comment]
closing as MR were merged

**Comment by CharStiles** [comment]
What file did you change to close this? I am having the same problem in my project i want to know which file I need to update. thank you.
