### ISSUE TITLE
Fixed and Extended 1.5.1 Build

### ISSUE THREAD

**Issue by chrigi** [jeromeetienne/AR.js#246]
Hello

As there were quite a few issues/improvements we needed for our project and the relevant pull requests (#212 and #168) are not merged yet, I merged them myself and rebuilt the 1.5.1 version including these fixes. Some of you might be interested in a simple release build so I have attached my fixed version.

This version fixes:
- Custom Markers
- Portrait Mode on mobile phones

This version adds:
- A 'marker-found' and 'marker-lost' event which is thrown by the a-marker component

Notes regarding custom pattern that I found helpful:
- Beside `type="pattern"` on your a-marker you will need to use `url=` and **not** `patternurl=`.
- Your Marker needs a white or almost white background (we used (254, 254, 254)). If you have a transparent background, the generator will generate an incorrect .patt file.

Notes regarding the new events:
- Done according to https://github.com/donmccurdy/aframe-extras/issues/180
- They will only be thrown once, every time the marker is found or lost.
- You can listen for them by attaching an event listener with addEventListener to the a-marker element.

(I know this is not a technically a bug but I though this might help some people turning to the issue tracker looking for help)
(Had to attach .txt to the files otherwise I could not upload them)

[aframe-ar.js.txt](https://github.com/jeromeetienne/AR.js/files/1477895/aframe-ar.js.txt)
[aframe-ar.min.js.txt](https://github.com/jeromeetienne/AR.js/files/1477896/aframe-ar.min.js.txt)
[ar.min.js.txt](https://github.com/jeromeetienne/AR.js/files/1477916/ar.min.js.txt)
[ar.js.txt](https://github.com/jeromeetienne/AR.js/files/1477917/ar.js.txt)
[babylon-ar.min.js.txt](https://github.com/jeromeetienne/AR.js/files/1477922/babylon-ar.min.js.txt)
[babylon-ar.js.txt](https://github.com/jeromeetienne/AR.js/files/1477923/babylon-ar.js.txt)
[artoolkit-webvr-polyfill.min.js.txt](https://github.com/jeromeetienne/AR.js/files/1477924/artoolkit-webvr-polyfill.min.js.txt)
[artoolkit-webvr-polyfill.js.txt](https://github.com/jeromeetienne/AR.js/files/1477925/artoolkit-webvr-polyfill.js.txt)

**Comment by javismiles** [comment]
Thank you Christian, this is great, is the fix for the custom marker same
as this code?

}else if( _this.data.preset === 'custom' ){
arProfile.defaultMarkerParameters.type = 'pattern'
arProfile.defaultMarkerParameters.patternUrl = _this.data.patternUrl;
arProfile.defaultMarkerParameters.markersAreaEnabled = false
}else {


the portrait fix is also a good one,

there is another issue I have, maybe you know why this happens, my marker
when detected activates and shows a video (I use a-frame with ar.js, so
aframe-ar),
I want to detect a click on that video element, not on the whole screen,
for some reason yes I can detect a click but its detected in the entire
whole screen, instead of just
in the video element itself, how can I make sure that it happens on the
video element itself?

Also I am using onclick events now because this used to work:

AFRAME.registerComponent('javi1', {
    init: function () {
      var el = this.el;
  el.addEventListener('click', function (evt) {... etc

but now its not working anymore  for some reason,

what's your recommended way to detect a click on the specific video element?

btw, in console Im receiving these 2 warnings, do they have any relation to
the issues with clicks?
"THREE.WebGLRenderer 87
pictoar1js.min.js:3 extras:primitives:warn Mapping keys should be specified
in lower case. The mapping key minConfidence may not be recognized
pictoar1js.min.js:3 extras:primitives:warn Mapping keys should be specified
in lower case. The mapping key hit-testing-renderDebug may not be
recognized "

thanks a lot


Ideami Studios
http://ideami.com
http://torchprinciple.com

**Comment by thehellrider** [comment]
Is it possible to trigger a sound when marker is detected and stop it when marker is lost using the event listener?

**Comment by letoast** [comment]
Sorr, but why was this set as invalid?

**Comment by chrigi** [comment]
I just checked the changes made since I posted this modified version.
It looks like the portrait fix and the custom marker fix were both merged into the code a while ago. Thanks a lot 😄 

The only thing still not merged are the events. There is an older pull request: https://github.com/jeromeetienne/AR.js/pull/303 which sadly has conflicts.

**Comment by EBKH** [comment]
@chrigi You said that 'the portrait fix' is merged, but it doesn't seem to work; Could you tell me in which doc or function a change is needed?

**Comment by chrigi** [comment]
@EBKH I think I just merged the changes I mentioned in my first post here: https://github.com/jeromeetienne/AR.js/pull/212
