### ISSUE TITLE
Not running on mobile devices

### ISSUE THREAD

**Issue by wheresmychutney** [jeromeetienne/AR.js#259]
<body style='margin : 0px; overflow: hidden;'>
        <a-scene stats="stats" embedded="embedded" arjs='trackingMethod: best;'>
            
            <a-marker-camera preset="hiro">
                <a-image listener geometry="primitive: plane" src="images/logo-ekya.png" rotation="-90 0 0" width="2" position='0 0 -2.5'></a-image>
                <a-text value="Ekya Open Day" rotation="-90 0 0" position="-0.5 0 -2" color="white"></a-text>
                <a-text value="Welcome to the AR Exhibit!" rotation="-90 0 0" position="-1 0 -1.5" color="white"></a-text>
            </a-marker-camera>
            <a-marker preset="kanji">
                <a-portal-door url="images/koper_slovenia.jpg" rotation="0 0 0"></a-portal-door>
            </a-marker-camera>
            <a-entity camera="camera"></a-entity>
                    </a-scene>
    </body>
</html>
``

Why does the above code work on my laptop but not on my phone?

**Comment by ZoltanVeres** [comment]
Can you be a little bit more specific? What kind of phone you have? Which demo page is not working for you?
Please also be aware that AR.js has two dependencies:
  - [getUserMedia](http://caniuse.com/#feat=stream) for the webcan
  - [WebGL](https://caniuse.com/#feat=webgl) for webgl

Please check them and make sure your browser has support for these features, otherwise i will have to close this issue.

**Comment by wheresmychutney** [comment]
the hiro and kanji work perfectly on my laptop,the ekya one i'm yet to figure that one .The hiro and kanji markers aren't recognized on any phone

**Comment by ZoltanVeres** [comment]
Make sure your browser supports these features:
 - [getUserMedia](http://caniuse.com/#feat=stream) for the webcan
  - [WebGL](https://caniuse.com/#feat=webgl) for webgl

Can you try and see if this example is working for you?

1. Open this [hiro marker image](https://jeromeetienne.github.io/AR.js/data/images/HIRO.jpg) in your desktop browser.
1. Open this [augmented reality webapps](https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html) in your phone browser, and point it

If not please specify your browser, otherwise we cannot help.

**Comment by wheresmychutney** [comment]
Google Chrome.This works.
that means there's a problem with my code.

**Comment by wheresmychutney** [comment]
And...yes.My browser supports the dependencies

**Comment by wheresmychutney** [comment]
Well it started working!Yay!

**Comment by RomitSingh1999** [comment]
@legitishan can you tell us what was the problem you were facing earlier, I am having the same issue tell us how you resolved your problem.
