### ISSUE TITLE
Bad performance on Firefox Mobile

### ISSUE THREAD

**Issue by sloschi** [jeromeetienne/AR.js#272]
Hi,

AR.js has a very bad performance ( ~2fps on a Google Pixel) on mobile firefox. Can anyone confirm this? And if yes, is there a solution? Or is firefox not supported right now?

**Comment by ZoltanVeres** [comment]
Hi @sloschi, thank you for your report. Currently @jeromeetienne is doing manual testing on many devices using webdriver, this is, because that's the most effective (end-to-end) way of testing AR is by doing it manually. Most of the tests were done on Android and iOS devices, none was executed on FireFox.
**We want to support all browsers however.**
Can you give use us some more details? Ex: which demo page you're experiencing the problem? What specific FF version are you having problems with? Test results and pointing us to some functions, which are extremely costly might help.

**Comment by sloschi** [comment]
You can try the [basic three.js example](https://jeromeetienne.github.io/AR.js/three.js/examples/basic.html).
I used the latest (v56) Firefox Version on the Play Store.

I tried the other examples and got mixed results. The best performance i had were ~20fps (which is still pretty low) in the [mobile performance](https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html) demo.

I started a remote debugging with WebIDE and recorded a [performance profile](https://github.com/jeromeetienne/AR.js/files/1526737/profile.zip), perhaps this will help.

**Comment by ZoltanVeres** [comment]
@sloschi if you look at the last sentence in this [TODO.md](https://github.com/jeromeetienne/AR.js/blob/master/TODO.md#profile). This perf. issue is mentioned, i think @jeromeetienne wants to fix it with WebAssembly. This issue also hits other browsers as well, but FireFox is happen to be affected more then the others.

**Comment by sloschi** [comment]
thanks for the info @ZoltanVeres 👍

**Comment by arjunmahishi** [comment]
also the camera is very blur in firefox

**Comment by nicolocarpignoli** [comment]
This PR has been closed due to inactivity for over one year. Please open a new, updated issue if the problem or the question is still relevant.
