### ISSUE TITLE
iOS 11.2 Webcam error:  WebRTC issue-! Navigator.mediaDevices not present in your browser

### ISSUE THREAD

**Issue by zerojuls** [jeromeetienne/AR.js#273]
Hello, I just tried it in the example (demo-firefox-release) with a iPhone 6 and I get the error "WebRTC issue-! Navigator.mediaDevices not present in your browser", I'm working with the Chrome browser, I've also tested on an iPhone 6s with safari browser and it works without problems. Both are actualized to iOS 11.2. I leave the error image that is seen in the browser.

![img-20171205-wa0000-2](https://user-images.githubusercontent.com/8573420/33614988-e198b728-d9a6-11e7-8fe6-a600873991dc.jpg)

![img-20171205-wa0001](https://user-images.githubusercontent.com/8573420/33615000-ec2674aa-d9a6-11e7-9a18-6397fa1eba91.jpg)

Any kind of help would be great, greetings!

**Comment by lslzl3000** [comment]
The same error in Wechat.
Maybe only safari support webtrc? Or other browsers use old version Navigator.getUserMedia as webrtc API, we should test it~

**Comment by ZoltanVeres** [comment]
According to this [Google support link](https://productforums.google.com/forum/#!topic/chrome/CkZPoDcJvjM) Chrome on iOS is using WKWebView which is basically a limited Safari version controlled entirely by Apple.
On iOS 11 Apple implemented the WebRTC protocol for Safari, but they didn't do it for WKWebView.
It's a shame because all non Safari browsers (Chrome, Firefox, etc) has to use WKWevView and even inApp browsers are constrained to this engine (ex: Facebook, WhatApp, etc). The only thing left for us is to press Apple to activate WebRTC in their WKWebView engine. From AR.js's point there's nothing we can do about it.

**Comment by chtidusud** [comment]
Dear all

From what I read on Apple's site, there is no plan to integrate shortly WebRTC support in WKWebView.
And I guess this lack of support is the reason why AR.js does not work under WeChat, which is certainly using this component as its browser.
By any chance, is there any alternative of web-based AR framework which does not use WebRTC ? we have a game to develop, but if we ask our customer to put aside all iOS users ... I am not sure they will welcome this information :-/
Thanks if you have any idea ! :-)

CDS

**Comment by meteorplus** [comment]
works totally fine if you open safari on ios 11 but not on chrome on ios 11 so use Safari instead which in most cases iphone users use 👍

**Comment by dusmant** [comment]
Does not look like iOS 11.2 has started supporting WebRTC on Safari... It still gives the error...getUserMedia() failed !!!

![safariwebrtcissue1](https://user-images.githubusercontent.com/6672411/34479655-07c8020e-efce-11e7-8ae5-cf8f45d6f857.jpg)

**Comment by ultradyran** [comment]
@meteorplus 

I am on iOS11 standalone safari browser and i still cant get this working. same error as mentioned above.

I m using some very simple code only, as taught in the ar.js landing page to load my model:

```
<!doctype HTML>
<html>
<script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="aframe-ar.js"></script>

<body style='margin : 0px; overflow: hidden;'>
    <a-scene stats embedded arjs='sourceType: webcam;'>

        <a-assets>
            <a-asset-item id="model" src="models/manekiinu.gltf" />
        </a-assets>
        <a-gltf-model src="#model" scale="0.01 0.01 0.01"></a-gltf-model>
        <!--<a-box material='color: black;'></a-box>-->
        <a-marker-camera preset='custom' type='pattern' patterUrl='ar.patt' url='ar.patt'>

        </a-marker-camera>
    </a-scene>
</body>

</html>
```

what i might hv missed?

**Comment by karneaud** [comment]
using iPhone SE with latest update of iOS 11 does not work in Safari nor Chrome

**Comment by AndresCuervo** [comment]
@cindyloo what glitch website are you trying to navigate to? One error that used to trip me up a lot was the site not using `https`, maybe check for that? @ultradyran same for you - it looks like your A-Frame + AR.js code is fine, but make sure you're accessing your website using `https://`, as only secure sites can access WebRTC so that they can ensure you aren't exposed to [man-in-the-middle attacks](https://developer.mozilla.org/en-US/docs/Glossary/MitM)

**Comment by commentatorboy** [comment]
I am a bit confused.
is webrtc not already compatible with most browsers?
or am I looking at the wrong one?
https://caniuse.com/#feat=rtcpeerconnection
https://caniuse.com/#feat=objectrtc

**Comment by AndresCuervo** [comment]
On iOS WebRTC is only available through Safari, is that what you've been
using?

**Comment by thecoconutstudio** [comment]
So are you saying AR.JS doesn't work with Ionic on iOS?

**Comment by commentatorboy** [comment]
@thecoconutstudio depends on the version of iOS.

**Comment by adi237** [comment]
@rpalmese Did you find any solution?
I am running it on IPhone XR with iOS 13.x.x and getting the same error.
Ionic-react-app.

**Comment by mslitto** [comment]
same here with iPhone 8 13.3

**Comment by Azleal** [comment]
same issue here
