### ISSUE TITLE
Video handling

### ISSUE THREAD

**Issue by boxgames1** [jeromeetienne/AR.js#281]
Hi, I have a question about play videos.

I have this piece of code:

```
<a-scene embedded arjs='sourceType: webcam;'> 
  <a-marker preset='hiro'> 
    <a-video id="inputVideo" src="test.mp4" width="2" height="2" position="0 0 0"></a-video> 
  </a-marker> 
  <a-entity camera> </a-entity> 
</a-scene>
```

The problem I have is that it plays the video after the page loads, and I want to play the video once the marker is scanned. Then paused if the marker is not visible.

I am trying to handle the event that makes visible the video, but can't find anything related in object3d.

On the other hand, `document.querySelector("video").pause() `doesn't work.

**Comment by ZoltanVeres** [comment]
@boxgames1 You violated our Issue template, so this question should be automatically deleted.
We also specify on the issue template that questions should be posted on stackoverflow, because there's a better chance to find a solution to your problem. I've made a search on Stackoverflow and i think [this will be usefull to you](https://stackoverflow.com/questions/44799413/how-to-detect-when-marker-is-found-in-ar-js). Please keep in your mind that AR.js is very complex and still is in his infancy, don't expect  that everything will work out of the box
