### ISSUE TITLE
Jerkiness smoothing

### ISSUE THREAD

**Issue by Erniastukas** [jeromeetienne/AR.js#311]
I'm in the middle of the project using AR.js, everything seems to go well, except the heavy jerkiness of the content (video over a poster with marker).

Is there any way to smooth out the motion of the A-camera? Where should I start to look for options in the code? I think simple position averaging over N number of frames would do the job.

**Comment by MrRaam** [comment]
@Erniastukas  Any update on this ?

**Comment by Erniastukas** [comment]
I've been on a very short schedule with the project and didn't managed to find out in which part of code the actual camera position updating is happening. If someone could point me where to dig - I could allocate some hours to making it happen.

**Comment by dreinstein10** [comment]
@Erniastukas , this might be what you are looking for:  #263 
Unfortunately it hasn't been merged yet. I want to try it myself, but I haven't had time to implement it on my code.

**Comment by cesarmiguel85** [comment]
I have the same problem as you @Erniastukas : I am trying to play a video over a poster (to generate virtual "TV"s on the wall) but the jerkiness is unbearable! Specially when looking at the marker without an angle (right from the front).
The shakiness is not that visible on 3d objects, specially when you animate them (it is there, but the eye does not catch it that much). But on planes... Oh gosh is it visible!

You can set the refresh rate as a parameter of the a-scene, but that does make the experience cluncky overall, so it's not a good solution... I wish this smoothing would be a parameter that could be easily set up... :-S

**Comment by hoktok** [comment]
Same problem here on mobile phones and tablets same for iOS and Android with PNG and SVG on a plane in aframe through AR.js Marker. Same for hiro, own markers.

For a professinal solution I am not satisfied and so I started painful tests to help me and others a little:

1. I found out that landscape mode is doing pretty OK, thats what aframe was invented for: VR. Seems nobody optimized aframe and AR.js for portrait mode on mobile phones. Portrait mode turns planes up to 90 degrees and sometimes does not flip back, so you are forced to use landscape or restart.

2. Aframe scale in a-image produces less jitter, when scaled in sync, e.g. scale="1 1 1" or scale="2.34 2.34 2.34".

3. The light is an important factor. It can change your markers look due to shadows and reflections if used on a screen. Constant light sources are a blessing.

4. Markers below 3 cm2 in the real world let the content shake more than bigger markers. Distances bewtween camera and marker below 40cm are ok, higher work better with bigger markers.

5. The white area around the thick black marker border should be at least half the borders width.
