### ISSUE TITLE
Artoolkit site can’t be reached

### ISSUE THREAD

**Issue by normancarcamo** [jeromeetienne/AR.js#316]
Does anybody know why the website of the project "ARToolKit" is down?

[](https://artoolkit.org/)

**Comment by jvijaybhaskar** [comment]
@normancarcamo As you might be aware back in 2015, ARToolkit was acquired by DAQRI ... i suppose they are consolidating their assets now .. 
I am not very sure what it means for ARToolik open source libraries per say. Though DAQRI did promise to continue investing ARToolkit, the current move indicates otherwise.

**Comment by linhdoha** [comment]
They're acquired by Daqri and ARToolKit website has been shut down.

**Comment by normancarcamo** [comment]
I understand, thanks!.
