### ISSUE TITLE
Not working properly https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js

### ISSUE THREAD

**Issue by nicogon** [jeromeetienne/AR.js#354]
Examples not working properly on samsung s7 aframe.

But with https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js works like charm

**Comment by nicolocarpignoli** [comment]
https://jeromeetienne.github.io/AR.js/aframe/build/aframe-ar.js  is `1.6.0` release of AR.js, so I guess it fixed some bugs on 1.5.0, that was released one year ago. Why not use 1.6.0 or at least 1.5.5 version?

**Comment by nicogon** [comment]
Its on the readme.md
People (like me) copy that Example to learn how to use this library

**Comment by nicolocarpignoli** [comment]
The only problem with this project is its maintenance. Although there was a release 23 days ago, I don't see support by authors on issues and Readme and documentation is poorly maintained and very obsolete.

I will open an issue hoping someone can do something about this because it's such a great project and it's a bit frustrating to look for examples and readme to find out they don't work or don't exist.

**Comment by nicolocarpignoli** [comment]
will fix this as we are working on new Readme
