### ISSUE TITLE
Move chat to slack

### ISSUE THREAD

**Issue by jeromeetienne** [jeromeetienne/AR.js#376]
Move chat to slack, thus we can get channel

**Comment by janpio** [comment]
ping, piotrowski+slack@gmail.com

**Comment by nicolocarpignoli** [comment]
@janpio sadly author of AR.js is not responding to chat/email for a long time. I cannot add you on github contributor so Is kinda useless :(

**Comment by janpio** [comment]
I am fine with going the normal Pull Request route, but a way to ask what stuff is already in the works, planned etc might be valuable anyway.

**Comment by nicolocarpignoli** [comment]
Yea, problem is actually nothing is planned. I don't see any commitment actually..

**Comment by janpio** [comment]
Ok.

I am interested in keeping AR.js alive as I used it in a project, and the current state of the repo is not optimal for "selling" the usage of AR.js to clients. Even if there is no big future development, it would still make sense to get the current working software in a better environment.

There was some work started to migrate the repo to an org in the past, but if I understood correctly this was stopped because old URLs might stop working or something like that. Maybe we should just start there ("move AR.js to the org") and investigate the best way so things don't break while doing this, and then try to get @jeromeetienne to go through with the transfer - including admin rights for you.

Right direction?

**Comment by nicolocarpignoli** [comment]
Could be the right direction. We started a slack chat. Some were invited, but then nobody has started with the commitment - if not for someone, also this is probably due to lack of 'direction', absolutely not to blame anyone.

We can start again to try to do things done this time. Otherwise the other path is to create a brand new repository and try to re-direct people from this one, that could be flagged as obsolete.

I'd like to know thoughts from people on AR.js slack:

**Comment by janpio** [comment]
I created https://github.com/jeromeetienne/AR.js/issues/469 so this is an independent issue and we don't abuse this one about Slack.

**Comment by JoseHervas** [comment]
@jeromeetienne @nicolocarpignoli can I join the slack?

jhervasdiaz@gmail.com

**Comment by nicolocarpignoli** [comment]
@JoseHervas slack is not used anymore, we are using this: request access https://trello.com/b/63F7JlvD/arjs
