### ISSUE TITLE
Why webRTC?

### ISSUE THREAD

**Issue by nikkwong** [jeromeetienne/AR.js#40]
Seems like projects such as 

https://github.com/argonjs/argon

or 

https://github.com/awe-media/awe.js

don't need webRTC. Why does ar.js require it?

Thx.

**Comment by jeromeetienne** [comment]
because webrtc is the way to read the webcam on a web page. and ar.js needs the video to find the markers. 

You should ask them how they do it :)

argon has a specific app to install and use a closesource/for-a-fee tracking. Nothing much to do with a opensource library for the web.

and i dunno awe.js, their homepage seems down. but if they run in a web browser, they need webrtc :)

i hope this helps.

**Comment by nikkwong** [comment]
Thx!
