### ISSUE TITLE
Running on webserver offline

### ISSUE THREAD

**Issue by alejokalderon** [jeromeetienne/AR.js#432]
Hi,

Sorry but I want to implement an AR solution on a webserver that works for a rural school that not have internet connection ¿is this possible with AR.js? Sorry if it not is the place for a question, please if you could give me a better contact channel I will be so grateful. 

Regards!

**Comment by nicolocarpignoli** [comment]
Hi!
It can be done! See here: https://github.com/nicolocarpignoli/nicolocarpignoli.github.io/blob/master/ar-playground/index.html.

Instead of loading scripts from remote, you can include Ar.js script files on the folder of your project 

```
   <script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
    <script src="https://rawgit.com/jeromeetienne/AR.js/master/aframe/build/aframe-ar.min.js"></script>
    <script src="https://rawgit.com/donmccurdy/aframe-extras/master/dist/aframe-extras.loaders.min.js"></script>
```

instead:

```
   <script src="<your-folder>/aframe.min.js"></script>
    <script src="<your-folder>/aframe-ar.min.js"></script>
    <script src="<your-folder>/aframe-extras.loaders.min.js"></script>
```

This way it can be possible to run your project on a local server. :)

For more quick responses, there is a chat, try to ask there: https://gitter.im/AR-js/Lobby

Good luck!

**Comment by droid001** [comment]
Or you could pack you deliver your project as a progressive web app. I'm giving [this webxr boilerplate](https://github.com/digaverse/webxr-webpack-boilerplate) a go.
