### ISSUE TITLE
I have reverse-engineered AR-Code Source Code

### ISSUE THREAD

**Issue by navanchauhan** [jeromeetienne/AR.js#514]
**Is your feature request related to a problem? Please describe.**
Nope

I have asked Jerome if I can reverse-engineer it or not.  If he gives a positive response, then I will upload it on a repo of mine

**Why?**

The generated PDF says that iOS is not supported, to update this and some other minute things I reverse-engineered it

**Comment by nicolocarpignoli** [comment]
Hi
you mean this? https://jeromeetienne.github.io/AR.js/three.js/examples/arcode.html
Explain better what is your aim, please. Also, If this is not a question/bug/proposal maybe it is better to discuss it on ar.js gitter or trello rather than on an issue, in my opinion :)

(good luck with that, in any case, I have no luck in getting responses from jerome in the last year)

**Comment by navanchauhan** [comment]
smh, I could not find it before

Closing the issue
