### ISSUE TITLE
Camera permission not granted

### ISSUE THREAD

**Issue by nicolocarpignoli** [jeromeetienne/AR.js#548]
I found this problem with last chrome (75) and also latest Safari

![image](https://user-images.githubusercontent.com/22395670/60341965-781d7100-99b0-11e9-9c2e-a15ed3f27ef0.png)

Important: there is **no debug log on console**, and the problem has suddenly shown up **only in Desktop Browsers**: fortunately on android (with chrome 75, so latest one) still works.

Did anyone experienced this as well?

It breaks codepen example on Readme of AR.js and other AR.js apps that were working last days.

**Comment by nicolocarpignoli** [comment]
I have problems also in local environment, with or withouth HTTPS makes no difference

**Comment by nicolocarpignoli** [comment]
examples: on github.io https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html

on codepen: https://codepen.io/nicolocarpignoli/pen/vMBgob

**Comment by nicolocarpignoli** [comment]
broken webcam! better this way🙂

**Comment by iggykov** [comment]
<img width="1440" alt="Screenshot 2019-07-08 at 19 35 09" src="https://user-images.githubusercontent.com/52668638/60830458-8ee57400-a1b7-11e9-8e7b-f05ecab87475.png">
Hi Nicolo! I have a similar problem when clicking learn new marker area. Do you know how to overcome this?

**Comment by iggykov** [comment]
in my browser the link works very well:
examples: on github.io https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html

but this one has the same issue: MarkersAreaEmabled :false
on codepen: https://codepen.io/nicolocarpignoli/pen/vMBgob

**Comment by nicolocarpignoli** [comment]
some things to try:

* your camera is ok?
* you have a laptop and possibly you are running the code with the laptop close and an external display (so camera is ok but cannot be found) ?
* try with another browser and tell us which browsers work and which not
* clean browser cache

**Comment by iggykov** [comment]
Hey Nicolo!
Thanks for your answer.
It means a lot to me, since I am a total beginner with programming and it is not easy to start, becouse I feel like I am annoying everyone around with basic questions :).

So for the link: https://codepen.io/nicolocarpignoli/pen/vMBgob
Safari - works
Firefox - works
Chrome - doesn't work (cam fires but no AR on the Hiro-marker).

_____
Answering your other Q:
Ad. cam:
Camera works perfectly with other browsers on your yellow-cube codepen demo and as mentioned with the following link it works in all browsers
https://jeromeetienne.github.io/AR.js/three.js/examples/mobile-performance.html
- so I guess the cam is generally ok.

Ad. ext. display:
I am using no external display, just laptop and the build-in webcam.

Ad. chache:
Browser cache in Chrome is cleaned -
still your yellow-cube demo https://codepen.io/nicolocarpignoli/pen/vMBgob doesn't work in Chrome

___
In addition I copied the code from https://codepen.io/nicolocarpignoli/pen/vMBgob to SublimeText, saved as index.html and opened it locally with all 3 browsers. Here the effect:
A) Firefox worked perfectly
B) Safari gave me this (where should i change it?):

> Webcam Error
> Name: NotAllowedError
> Message: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

C) Chrome fires the website and the cam but no AR occurs.

--------
Maybe it is a different topic but I wonder if you could give me guidance on this:
What is this message on the screen:
> MarkersAreaEnabled :false - what does this mean?
I noticed that it disappears, when i try to put a custom marker...
Then there are some buttons like: 
- Toggle MArker Helper
- Learn New Marker Area
- Reset Marker Area
Do you know any link that explains this features to beginners?

**Comment by nicolocarpignoli** [comment]
For the last question, use this 
`<a-scene embedded arjs='sourceType: webcam; debugUIEnabled: false; >`
instead of the a-scene currently used. this will disable debug buttons and text.

For the safari error, it is strange, safari should asks you camera permission at any website refresh.

Chrome works for me also. Which device are you using? I suggest you to run the example on smartphone and show hiro marker on screen (laptop or whatever)
