### ISSUE TITLE
AR.js Marker Training Border color not working with iphone

### ISSUE THREAD

**Issue by jamess922** [jeromeetienne/AR.js#550]
Hi：
    I tried with the [Border color setting ](https://jeromeetienne.github.io/AR.js/three.js/examples/marker-training/examples/generator.html)，I feel it‘s so great if we could use other colors,not only black. so i use red to try,but faild,alos try with other colors still faild ,if come back to black, it's working,so sad
Iphone 7   
IOS 12

**Comment by jamess922** [comment]
I need to use a dark one

**Comment by nicolocarpignoli** [comment]
Hi, what you mean with 'failed'?

We lately added such feature because we saw, testing it, that it works with dark colors, aka colors with high contrast with the contrast used inside the image.

So, your border color MUST have an high contrast with the color of the pattern image.
Otherwise, it won't work.
Please, post here your full marker, the one that works with black and also the one that doesn't work, so we can help you

**Comment by jamess922** [comment]
'failed' means  the model dose not show
![3](https://user-images.githubusercontent.com/28625879/60493777-293d4780-9ce0-11e9-8c86-72f8d84fc5b7.png)
I just testing with Android ，it's working  with red Border  and red the pattern image
![QQ截图20190702154617](https://user-images.githubusercontent.com/28625879/60494002-8fc26580-9ce0-11e9-86fa-43ba06eed77a.png)

**Comment by nicolocarpignoli** [comment]
yea, this way it works, because the red border has an high contrasts with the white of the inner image. Glad to know it's solved !

**Comment by jamess922** [comment]
but  not working with iphone

**Comment by jamess922** [comment]
only Android working well

**Comment by jamess922** [comment]
@

**Comment by nicolocarpignoli** [comment]
send screenshot, and also send console.logs if there is some log
