### ISSUE TITLE
Auto Light Estimation (Three.js)

### ISSUE THREAD

**Issue by JannickLeismann** [jeromeetienne/AR.js#568]
Hey there,
it would be amazing to have automatic light estimation. Right now it's hard to make an object look realistic since the lighting need to get set manually.

Are there any future plans on adding something like this?

I found a video where someone did this with a pingpong-ball but that's not what i call automatic.

Kind regards

**Comment by 0b01001101** [comment]
I build a lib for location-based ar with includes light estimation based on the AmbientLightSensor API https://developer.mozilla.org/en-US/docs/Web/API/AmbientLightSensor

For a live example see: https://0b01001101.github.io/locationar/examples/ambientlight.html

The use "in production" is limeted, because the Chrome flag #enable-generic-sensor-extra-classes need to be enabled in the current version [Chrome 75]

**Comment by nicolocarpignoli** [comment]
Closing this issue due to dismission of this repository. New repository of AR.js will be up at https://github.com/AR-js-org/AR.js/

Feel free to re-open the issue there if still valid.
