### ISSUE TITLE
videoLuma in original artoolkit.api.js is needed,why you can delete this?

### ISSUE THREAD

**Issue by allrightzhu** [jeromeetienne/AR.js#577]
I find that videoLuma in your artoolkit.api.js is deleted,but when I try to delete videoLuma 
 in my own artoolkit.api.js then the marker can't work.Do you modify the original jsartoolkit? if you did it's  that possible to opensource the modified artoolkit?

**Comment by kalwalt** [comment]
@allrightzhu The problem is that we don't know  which version is from here https://github.com/artoolkit/jsartoolkit5
or from the new https://github.com/artoolkit/jsartoolkit5
In my opinion from the first, because the jsartoolkit5 from artoolkitx has wasm support and the first from https://github.com/artoolkit/jsartoolkit5 has not. But it could be also modified by @jeromeetienne  but we don't know this...
Anyway can you explain how you deleted videoLuma? I Can not understand this...

**Comment by allrightzhu** [comment]
Thanks for you answer, I found the difference you said，I got an version from [https://github.com/kalwalt/jsartoolkit5/tree/fixing-nft](https://github.com/kalwalt/jsartoolkit5/tree/fixing-nft)，
I found that fixing-nft version didn't work efficient，but the ar.js can work very well， I want to find the reason why the  fixing-nft version got low FPS.

**Comment by kalwalt** [comment]
https://github.com/kalwalt/jsartoolkit5/tree/fixing-nft is a development branch about **nft**, it has low performace because in the last commit i added a non threaded routine that drops a lot the fps while detecting nft markers. I think i will remove the last changes. 
About VideoLuma: in artoolkitx/jsartoolkit5 you don't need to include VideoLuma https://github.com/artoolkitx/jsartoolkit5/pull/79 for the other version (the older)https://github.com/artoolkit/jsartoolkit5/ i don't know. I always worked on https://github.com/artoolkitx/jsartoolkit5, the most updated...

**Comment by allrightzhu** [comment]
@kalwalt thanks for your working on nft, more people are looking at nft,hope that you can make a high FPS version with jsartoolkit-nft... good luck for you,and I will work on this too,although I am a newbie~
