### ISSUE TITLE
something wrong with AR.js 1.7.8?

### ISSUE THREAD

**Issue by HolyZheng** [jeromeetienne/AR.js#586]
10 line demo on the readme
```
<-- this demo using AR.js 1.7.8 can not work -->
<!doctype HTML>
<html>
<script src="https://aframe.io/releases/0.9.2/aframe.min.js"></script>
<script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.7.8/aframe/build/aframe-ar.js"></script>
  <body style='margin : 0px; overflow: hidden;'>
    <a-scene embedded arjs>
      <a-marker preset="hiro">
          <a-box position='0 0.5 0' material='color: yellow;'></a-box>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
```
If you copy that to codepen, you will find it is not working.
And when I open the codepen default demo on the readme, it is working , the version of AR.js used in the copepen default demo is 1.7.5.

So, if something wrong with AR.js 1.7.8 , or just the demo using 1.7.8 at readme does something wrong?

**Comment by nicolocarpignoli** [comment]
Hi, thanks for finding this.
The problem is that cdn.rawgit URLs are no longer available and sometimes might not work properly. We should use raw.githack.
For some reason, with 1.7.8 something went wrong with the release, and I'm not able to get a direct raw.githack URL as for the other AR.js minified versions.

So the answer is: version 1.7.8 is fine but not the way of importing it with raw.githack. You should use version 1.7.7. I could think to revert back version 1.7.8 but i have no time at the moment unfortunately.

I will update the Readme with the usage of 1.7.7.
