### ISSUE TITLE
Not receiving Geolocation Alert on iOS 12.x

### ISSUE THREAD

**Issue by rdub80** [jeromeetienne/AR.js#607]
**Describe the bug**
The geolocation information is not retrieved in the scene - `gps-entity-place` default to pos 0 0 0 or don't show up at all

**Smartphone (please complete the following information):**
 - Device: iPhone6 and iPhone11
 - OS: iOS 13.1
 - Browser Safari
 - Version 12.x and 13.x

**Comment by nicolocarpignoli** [comment]
Hi @rdub80, just one clarification: above as OS you specified iOS 13.1 but you mention as browser both safari 12 and 13. Are you sure the problem is also on safari 12.* ? Because safari versions are the same as iOS. 

Anyway, for iOS 13 the problem is the same as https://github.com/nicolocarpignoli/GeoAR.js/issues/12: will look into it.
