### ISSUE TITLE
Always place object horizontal (use marker only to detect the point, but not the surface)

### ISSUE THREAD

**Issue by taime** [jeromeetienne/AR.js#645]
Is it possible to ignore the surface of marker, and only use it to find the point where to place the object?

I want always place the object like if marker is horizontal (to use smartphone sensors for detecting horizontal surface).

It's the common case actually and this could dramatically reduce object shaking.

**Comment by nicolocarpignoli** [comment]
Hi
I try to answer to all:

- Is it possible to ignore the surface of marker, and only use it to find the point where to place the object?
the marker, in the marker-based way of AR.js, has to always be visible during the tracking.

- I want always place the object like if marker is horizontal (to use smartphone sensors for detecting horizontal surface).
To use smartphone sensors for detecting horizontal surfaces (planes) is a very advanced technology, actually not available on AR.js

- It's the common case actually and this could dramatically reduce object shaking.

I don't think object shaking could be resolved with this. Or, at least, object shaking is because marker is not recognized properly: you may have created a poor recognizable pattern marker or either are far from the marker.

Anyway, to show the AR content regardless marker orientation, you could use 'orientation' attribute on the a-entity used. It's a common thing to do and works great. 
https://aframe.io/docs/0.9.0/components/rotation.html

**Comment by taime** [comment]
@nicolocarpignoli Thanks, 
https://aframe.io/docs/0.9.0/components/rotation.html - it's rotation relative to marker surface, am I right?

My marker is always visible and well recognised, but I want ignore marker surface and use smartphone gravity sensors to find vertical, horizontal and use it to place the marker horizontal.
1) is it possible to use marker only for detecting point but not the surface?
2) is it possible to use smartphone gravity sensors to detect horizontal surface and use it for object orientation?

**Comment by taime** [comment]
@nicolocarpignoli Thanks,
https://aframe.io/docs/0.9.0/components/rotation.html - it's rotation relative to marker surface, am I right? I need the absolutely opposite. I want object to stand still vertically like objects in geo ar js ... But instead of geo coordinates I want use marker. So I will have object on marker bay without any shakes at all. Did you get the idea? 

My marker is always visible and well recognised, but I want ignore marker surface and use smartphone gravity sensors to find vertical, horizontal surfaces and use it for marker orientation.

is it possible to use marker only for detecting point but not the surface?
is it possible to use smartphone gravity sensors to detect horizontal surface and use it for object orientation?

**Comment by francescozanotti** [comment]
might not be exactly what you are looking for, but i managed to do something similar with [aframe-look-at-component](https://github.com/supermedium/superframe/tree/master/components/look-at)
`
<a-marker>
    <a-entity look-at="[camera]"></a-entity>
</a-marker>
<a-entity camera id="arjscamera"></a-entity>
`
the entity will always be "parallel" (oriented to camera rotation)

**Comment by felipenmoura** [comment]
Hi.
What about this?

- Detect the marker and set it as "the zero point in the world"
- Then use the gyroscope sensors to place objects in the scene

I mean...in this case, the user:
- would NOT be required to keep the marker visible in the camera, but could look (literaly) around
- would NOT be able to "walk" around, as it will not update the zero point based on GPS or anything.

I do believe this would offer a huge difference in UX for AR. This would be a mix of AR and VR controllers.

Is this already possible?

**Comment by nicolocarpignoli** [comment]
If bug still persist, please re-open at: https://github.com/jeromeetienne/AR.js
