### ISSUE TITLE
5x5 markers not being recognised

### ISSUE THREAD

**Issue by hillj8** [jeromeetienne/AR.js#730]
**Describe the bug**
3x3 and 4x4 markers are recognisde well by the system, but cannot seem to get 5x5 to be correctly identified.

**To Reproduce**
Definition of a-scene for 4x4
`
<a-scene embedded arjs='sourceType: webcam; detectionMode: mono_and_matrix; matrixCodeType: 4x4;'>`

and for 5x5

`<a-scene embedded arjs='sourceType: webcam; detectionMode: mono_and_matrix; matrixCodeType: 5x5;'>`

**Expected behavior**
Marker is recognised and window alert displayed with the ID of the marker. I.e. if marker number 18 is shown, 18 should be displayed.

**Screenshots**
4x4 - marker id 18 shown and correctly identified - works for all IDs

![image](https://user-images.githubusercontent.com/37069297/74333276-87123180-4d8f-11ea-8c0d-49db6899c322.png)

but with 5x5 - whilst a value is returned it is not the correct one, and many of the markers return the same id. For example 18 and 21 both return '1', and 25 and 40 both return 16 ect. (erratic incorrect identification.)

![image](https://user-images.githubusercontent.com/37069297/74333625-3818cc00-4d90-11ea-93e9-2ef04eff7f69.png)
![image](https://user-images.githubusercontent.com/37069297/74333629-39e28f80-4d90-11ea-85da-31a0f3d7f9da.png)

**Desktop (please complete the following information):**
Win 10, Firefox V 72

**Smartphone (please complete the following information):**
Using iPhone 7 camera passthrough 

**Additional context**

**Comment by kalwalt** [comment]
Hi @hillj8 5X5 markers are not supported by jsartoolkit5 see in the bindings here: 
https://github.com/artoolkitx/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/emscripten/ARBindEM.cpp#L101-L106
so because Ar.js depends by jsartoolkit5 do not support that kind of markers. We could add them in near future, this is not possible at the moment because:
- we don't know with which jsartoolkit5 version @jeromeetienne used to build the libs
- we are moving to the new version and we are focused now on NFT markers integrations, but after that i think we can add them, after Ar.js 3.0 release. 
:smile:

**Comment by nicolocarpignoli** [comment]
see on linked issue, this one has been moved on new AR.js repo.
