### ISSUE TITLE
webcam content part of canvas

### ISSUE THREAD

**Issue by atep77** [jeromeetienne/AR.js#734]
**Is your feature request related to a problem? Please describe.**
I am trying to capture the content of canvas, using this example https://webrtc.github.io/samples/src/content/capture/canvas-record/ but it captures only content of ar.js - for example the yellow box (after use of marker) but not the background (the background is captured WebM file is black) - the stream from the webcam.

**Describe the solution you'd like**
Why is the webcam content not a part of the canvas? Or am I missing something (as I am expecting :-) )

**Describe alternatives you've considered**
Or is it possible to set the content of canvas into "background"? 

**Additional context**
Here is my example: https://glitch.com/~rhinestone-turret-slrsh3lgga

Thank you very much

**Comment by nicolocarpignoli** [comment]
The webcam content is not part of the canvas. Is rendered as source of a video element. You can see it if you inspect the page with Dev Tools.

To take a screenshot of the entire image is very cumbersome: you have to combine both the video + canvas content.

Look here:
https://github.com/jeromeetienne/AR.js/issues/358

Closing because duplicate.

**Comment by atep77** [comment]
Thank you for response,
  I saw the #358 before, but it is a "little bit" complicated.. :) and I am not sure, if it possible to use it for video, but thanks anyway. 
   I tried this method (without background) on mobile ("old" samsung a5 with chrome) and it was horrible slow - so I think, it is not possible to solve this "quest" in this way.. but thanks again.
