### ISSUE TITLE
Movement inside of the room around 3d object after scanning marker only once. 

### ISSUE THREAD

**Issue by mazurmazurmazur** [jeromeetienne/AR.js#735]
Maybe I am going a bit too far outside of the box here, but do you think it is possible to achieve something like this: https://www.youtube.com/watch?v=94GcTYiiki0 ?
I managed to achieve disregarding marker after scanning it and allowing the 3D object to stay (and not be glued to the viewport like with a-marker-camera). But this 3D object still only reacts to rotation of my phone around camera's axis, and does not react when I walk to the sides or backward/forward. 
I have been browsing if it is possible to walk with the smartphone in hand and let accelerometer detect my movement in a-frame itself but without much success.

**Comment by nicolocarpignoli** [comment]
Not at the moment, with current technologies. What you are trying to achieve can be done with plane detection and technologies that scans the room, make a map of it, and memorize it, in order to 'remember' where the object was positioned. Something that you can achieve with future WebXR Device API. You could look into that. There  are no plans, as for now, for this feature on AR.js.
