### ISSUE TITLE
change camera on mobile

### ISSUE THREAD

**Issue by marcs7** [jeromeetienne/AR.js#96]
how is possible change the camera in rear camera from front camera ?

**Comment by jeromeetienne** [comment]
sorry i dont understand. can you elaborate ?

**Comment by MarS7** [comment]
i need to change the camera where i read the patter in my phone from front camera to a back camera like in this video https://www.youtube.com/watch?v=0MtvjFg7tik&feature=youtu.be

**Comment by MarS7** [comment]
any help?

**Comment by tetreault** [comment]
@jeromeetienne I'm having the same issue. The Hiro demo is cool but on a Nexus 6p it defaults to front facing camera pointed at me, not the rear camera making the demo sorta pointless. My main day-to-day phone is an iphone so idk how to switch front-facing camera for rear-facing in chrome on android.

**Comment by jeromeetienne** [comment]
i have a nexux6p at home and it load the demo without issue on the bend
camera

**Comment by tetreault** [comment]
Thanks for the quick reply @jeromeetienne. First and foremost, I appreciate your effort on trying to bring web ar to the world faster :). I really want to engage with AR.js, if for me it constantly just defaults to front facing camera I'm not sure what else I should be doing. Any tips? I'm continuing developing an AR.js demo for myself as well but am presuming I'll hit the same issue where it only uses front facing camera.

**Comment by MarS7** [comment]
You to change the facing mode into environment if you want change the camera

**Comment by patricknelson** [comment]
Actually the issue is more likely to be that `facingMode` isn't available in the version of Chrome for Android that you might be using. I happen to have two Galaxy S8's but mysteriously one worked (Chrome v59) and the other did not (Chrome v56). I tracked it down to issue [#290161 in Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=290161). 

Thankfully that means you have two easy fixes 👍😎 :

- Use a polyfill, https://github.com/webrtc/adapter. I can confirm this worked for me in Chrome v56.
- Upgrade Chrome on your device (better if you have control over your environment like I do).
